# Generated by Django 4.2.17 on 2024-12-07 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
    ]
