# Generated by Django 4.2.17 on 2024-12-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20241207_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='sculpture',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
