# Generated by Django 4.2.17 on 2024-12-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_sculpture_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sculpture',
            name='year',
        ),
        migrations.AlterField(
            model_name='sculpture',
            name='artist',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sculpture',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sculpture',
            name='image_url',
            field=models.URLField(),
        ),
    ]
